### PR TITLE
Bump version to 4.0.4 with specific file version.

### LINKED ISSUE #9: Please update the FileVersion when updating the ProductVersion or AssemblyVersion
If the `FileVersion` doesn't get bumped, the MSI installation of the Iesi.Collections.dll breaks down.

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Fixes #9

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
#9 may also be a trouble for NHibernate users willing to package it as a MSI.
So then we should publish this and make NHibernate use the latest NuGet of Iesi.

**Comment by fredericDelaporte** [comment]
@hazzik, do you agree with releasing this?

**Comment by oskarb** [comment]
FileVersion should ALWAYS be updated when the file is modified. ProductVersion and AssemblyVersion only sometimes.

https://nhibernate.jira.com/browse/NH-1890 have some history but seems irrelevant now. It's possible I overlooked the file version thing when I ported it to .Net 4.

+1

**Comment by fredericDelaporte** [comment]
The trap is due to `FileVersion` defaulting,  when not specified, to `AssemblyVersion`, which seems not well documented. We can find some false assumption on StackOverflow about `FileVersion` defaulting to `Version`, but that is true only if `AssemblyVersion` is not specified either.

**Pull request merged**
